version: "3"
services:
  web:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    logging:
      driver: none
    ports:
      - "27018:27017"
